services:
  - type: web
    name: intelligent-stroke-risk-assessment-system
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DATABASE_URL
        value: sqlite:///app.db
    disk:
      name: model-data
      mountPath: /opt/render/project/src/models
      sizeGB: 2 