"""Add phone_number and sms_notifications fields to User model

Revision ID: 407542429d39
Revises: 9527a9dc2a54
Create Date: 2025-04-20 17:02:50.040818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407542429d39'
down_revision = '9527a9dc2a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('sms_notifications', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sms_notifications')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
