"""Add profile, notification and privacy fields to User model

Revision ID: 9527a9dc2a54
Revises: 3b21e78ce9f7
Create Date: 2025-04-20 16:41:11.100113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9527a9dc2a54'
down_revision = '3b21e78ce9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('email_notifications', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('health_reminders', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('glucose_reminders', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('medication_reminders', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('app_updates', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('share_health_data', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('public_profile', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('data_retention', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'data_retention')
    op.drop_column('user', 'public_profile')
    op.drop_column('user', 'share_health_data')
    op.drop_column('user', 'app_updates')
    op.drop_column('user', 'medication_reminders')
    op.drop_column('user', 'glucose_reminders')
    op.drop_column('user', 'health_reminders')
    op.drop_column('user', 'email_notifications')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
